export interface IActaLista {
    fecharegistro : string,
    nombreusuario : string,
    usuario :string,
    conductorintervenido :string,
    tipodocinterv :string,
    numerodocinterv :string,
    direccioninterv :string,
    distritointerv :string,
    isvehiculoautorizado :number,
    empresaautorizada :string,
    ruc :string,
    numlicconducir :string,
    fechainfraccion :string,
    placa :string,
    lugarinfraccion :string,
    referenciainfra :string,
    distritoinfra :string,
    tipoinfraccion :string,
    codigoinfra :string,
    medidapreventiva :string,
    manifestacioninterv :string,
    descriphecho :string,
    observacionuno :string,
    observaciondos :string,
    clasecategoria :string,
    codigoResultado : number,
    nombreresultado :string
}

